// NOTE: AUTO-GENERATED by midc, DON'T edit!!

package model

import (
	"fmt"

	"github.com/midlang/mid/x/go/storage"
	"github.com/mkideal/pkg/typeconv"
)

var (
	_ = fmt.Printf
	_ = storage.Unused
	_ = typeconv.Unused
)

// Table

// 邮箱验证码
type EmailVerifyCode struct {
	Email     string `xorm:"pk VARCHAR(64)"`     // email 地址
	Code      string `xorm:"VARCHAR(64) UNIQUE"` // 验证码
	CreatedAt string `xorm:"VARCHAR(32)"`        // 创建时间
	ExpireAt  string `xorm:"VARCHAR(32)"`        // 到期时间

}

func NewEmailVerifyCode() *EmailVerifyCode {
	return &EmailVerifyCode{}
}

func (EmailVerifyCode) Meta() storage.TableMeta { return EmailVerifyCodeMetaVar }
func (x EmailVerifyCode) Key() interface{}      { return x.Email }
func (x *EmailVerifyCode) SetKey(value string) error {
	x.Email = value
	return nil
}

func (x EmailVerifyCode) GetField(field string) (interface{}, bool) {
	switch field {
	case EmailVerifyCodeMetaVar.F_code:
		return x.Code, true
	case EmailVerifyCodeMetaVar.F_created_at:
		return x.CreatedAt, true
	case EmailVerifyCodeMetaVar.F_expire_at:
		return x.ExpireAt, true
	}
	return nil, false
}

func (x *EmailVerifyCode) SetField(field, value string) error {
	switch field {
	case EmailVerifyCodeMetaVar.F_code:
		x.Code = value
	case EmailVerifyCodeMetaVar.F_created_at:
		x.CreatedAt = value
	case EmailVerifyCodeMetaVar.F_expire_at:
		x.ExpireAt = value
	}
	return nil
}

// Meta
type EmailVerifyCodeMeta struct {
	F_code       string
	F_created_at string
	F_expire_at  string
}

func (EmailVerifyCodeMeta) Name() string     { return "email_verify_code" }
func (EmailVerifyCodeMeta) Key() string      { return "email" }
func (EmailVerifyCodeMeta) Fields() []string { return _email_verify_code_fields }

var EmailVerifyCodeMetaVar = &EmailVerifyCodeMeta{
	F_code:       "code",
	F_created_at: "created_at",
	F_expire_at:  "expire_at",
}

var _email_verify_code_fields = []string{
	EmailVerifyCodeMetaVar.F_code,
	EmailVerifyCodeMetaVar.F_created_at,
	EmailVerifyCodeMetaVar.F_expire_at,
}

// Slice
type EmailVerifyCodeSlice []EmailVerifyCode

func NewEmailVerifyCodeSlice(cap int) *EmailVerifyCodeSlice {
	s := EmailVerifyCodeSlice(make([]EmailVerifyCode, 0, cap))
	return &s
}

func (s EmailVerifyCodeSlice) Len() int                                  { return len(s) }
func (s EmailVerifyCodeSlice) ReadonlyTable(i int) storage.ReadonlyTable { return s[i] }
func (s *EmailVerifyCodeSlice) Slice() []EmailVerifyCode                 { return []EmailVerifyCode(*s) }

func (s *EmailVerifyCodeSlice) New(table string, index int, key string) (storage.FieldSetter, error) {
	for len(*s) <= index {
		*s = append(*s, EmailVerifyCode{})
	}
	x := &((*s)[index])
	err := x.SetKey(key)
	return x, err
}

// View
type EmailVerifyCodeView struct {
	EmailVerifyCode
}

type EmailVerifyCodeViewSlice []EmailVerifyCodeView

func NewEmailVerifyCodeViewSlice(cap int) *EmailVerifyCodeViewSlice {
	s := EmailVerifyCodeViewSlice(make([]EmailVerifyCodeView, 0, cap))
	return &s
}

func (s *EmailVerifyCodeViewSlice) Slice() []EmailVerifyCodeView {
	return []EmailVerifyCodeView(*s)
}

func (s *EmailVerifyCodeViewSlice) New(table string, index int, key string) (storage.FieldSetter, error) {
	if table == "email_verify_code" {
		for len(*s) <= index {
			x := EmailVerifyCode{}
			*s = append(*s, EmailVerifyCodeView{EmailVerifyCode: x})
		}
		x := &((*s)[index].EmailVerifyCode)
		err := x.SetKey(key)
		return x, err
	}
	v := &((*s)[index])
	for t, x := range v.tables() {
		if t == table {
			err := x.SetKey(key)
			return x, err
		}
	}
	return nil, storage.ErrTableNotFoundInView
}

var (
	EmailVerifyCodeViewVar  = EmailVerifyCodeView{}
	emailVerifyCodeViewRefs = map[string]storage.View{}
)

func (EmailVerifyCodeView) Table() string { return EmailVerifyCodeMetaVar.Name() }
func (EmailVerifyCodeView) Fields() storage.FieldList {
	return storage.FieldSlice(EmailVerifyCodeMetaVar.Fields())
}
func (EmailVerifyCodeView) Refs() map[string]storage.View { return emailVerifyCodeViewRefs }
func (view *EmailVerifyCodeView) tables() map[string]storage.WriteonlyTable {
	m := make(map[string]storage.WriteonlyTable)
	m["email_verify_code"] = &view.EmailVerifyCode
	return m
}
