/* NOTE: AUTO-GENERATED by midc, DON'T edit!! */

CREATE TABLE IF NOT EXISTS `user` (
	`id` BIGINT(20)   COMMENT '随机唯一Id',
	`account_type` BIGINT(20)   COMMENT '账号类型',
	`account` TEXT   COMMENT '账号',
	`nickname` TEXT   COMMENT '昵称',
	`avatar` TEXT   COMMENT '头像',
	`qrcode` TEXT   COMMENT '二维码',
	`gender` BIGINT(20)   COMMENT '性别',
	`birthday` TEXT   COMMENT '生日',
	`id_card_type` BIGINT(20)   COMMENT '身份证件类型',
	`id_card` TEXT   COMMENT '证件唯一标识',
	`encrypted_password` TEXT   COMMENT '加密后密码',
	`password_salt` TEXT   COMMENT '加密密码的盐',
	`created_at` TEXT   COMMENT '账号创建时间',
	`created_ip` TEXT   COMMENT '账号创建时IP',
	`last_login_at` TEXT   COMMENT '最后登陆时间',
	`last_login_ip` TEXT   COMMENT '最后登陆时IP',
	PRIMARY KEY (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `client` (
	`id` TEXT   ,
	`secret` TEXT   ,
	`name` TEXT   ,
	`scope` TEXT   ,
	`description` TEXT   ,
	`callback_url` TEXT   ,
	PRIMARY KEY (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `access_token` (
	`id` BIGINT(20)   COMMENT '递增唯一Id',
	`uid` BIGINT(20)   COMMENT '用户Id',
	`created_at` TEXT   COMMENT '创建时间',
	`modified_at` TEXT   COMMENT '修改时间',
	`expire_at` TEXT   COMMENT '到期时间',
	`token` TEXT   COMMENT '令牌',
	`refresh_token` TEXT   COMMENT '刷新用令牌',
	`resource_owner` TEXT   COMMENT '资源所有者',
	`client_id` TEXT   COMMENT '客户Id',
	`scope` TEXT   COMMENT '可访问权限范围',
	PRIMARY KEY (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `authorization_request` (
	`id` BIGINT(20)   COMMENT '递增唯一Id',
	`created_at` TEXT   COMMENT '创建时间',
	`authorization_code` TEXT   COMMENT '认证码',
	`uid` BIGINT(20)   COMMENT '用户Id',
	`redirect_uri` TEXT   COMMENT '重定向URI',
	`response_type` TEXT   COMMENT '返回类型',
	`state` TEXT   COMMENT '自定义状态',
	`client_id` TEXT   COMMENT '客户端Id',
	`granted_scopes` TEXT   COMMENT '授权范围',
	`requested_scopes` TEXT   COMMENT '请求范围',
	PRIMARY KEY (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `telno_verify_code` (
	`id` BIGINT(20)   COMMENT '递增唯一Id',
	`telno` TEXT   COMMENT '手机号码',
	`code` TEXT   COMMENT '验证码',
	`expired_at` TEXT   COMMENT '到期时间',
	PRIMARY KEY (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `email_verify_code` (
	`id` BIGINT(20)   COMMENT '递增唯一Id',
	`email` TEXT   COMMENT 'email 地址',
	`code` TEXT   COMMENT '验证码',
	`expired_at` TEXT   COMMENT '到期时间',
	PRIMARY KEY (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `session` (
	`id` TEXT   ,
	`uid` BIGINT(20)   ,
	`expire_at` TEXT   ,
	PRIMARY KEY (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

