// NOTE: AUTO-GENERATED by midc, DON'T edit!!

package model

import (
	"fmt"

	"github.com/mkideal/pkg/storage"
	"github.com/mkideal/pkg/typeconv"
	"gopkg.in/redis.v5"
)

var (
	_ = fmt.Printf
	_ = storage.Unused
	_ = typeconv.Unused
	_ = redis.Nil
)

// Table

// 手机验证码
type TelnoVerifyCode struct {
	Telno     string `xorm:"pk VARCHAR(32)"` // 手机号码
	Code      string `xorm:"VARCHAR(8)"`     // 验证码
	CreatedAt string `xorm:"VARCHAR(32)"`    // 创建时间
	ExpireAt  string `xorm:"VARCHAR(32)"`    // 到期时间

}

func NewTelnoVerifyCode() *TelnoVerifyCode {
	return &TelnoVerifyCode{}
}

func (TelnoVerifyCode) Meta() TelnoVerifyCodeMeta    { return telnoVerifyCodeMetaVar }
func (TelnoVerifyCode) TableMeta() storage.TableMeta { return telnoVerifyCodeMetaVar }
func (x TelnoVerifyCode) Key() interface{}           { return x.Telno }
func (x *TelnoVerifyCode) SetKey(value string) error {
	x.Telno = value
	return nil
}

func (x TelnoVerifyCode) GetField(field string) (interface{}, bool) {
	switch field {
	case telnoVerifyCodeMetaVar.F_code:
		return x.Code, true
	case telnoVerifyCodeMetaVar.F_created_at:
		return x.CreatedAt, true
	case telnoVerifyCodeMetaVar.F_expire_at:
		return x.ExpireAt, true
	}
	return nil, false
}

func (x *TelnoVerifyCode) SetField(field, value string) error {
	switch field {
	case telnoVerifyCodeMetaVar.F_code:
		x.Code = value
	case telnoVerifyCodeMetaVar.F_created_at:
		x.CreatedAt = value
	case telnoVerifyCodeMetaVar.F_expire_at:
		x.ExpireAt = value
	}
	return nil
}

// Meta
type TelnoVerifyCodeMeta struct {
	F_code       string
	F_created_at string
	F_expire_at  string
}

func (TelnoVerifyCodeMeta) Name() string     { return "telno_verify_code" }
func (TelnoVerifyCodeMeta) Key() string      { return "telno" }
func (TelnoVerifyCodeMeta) Fields() []string { return _telno_verify_code_fields }

var telnoVerifyCodeMetaVar = TelnoVerifyCodeMeta{
	F_code:       "code",
	F_created_at: "created_at",
	F_expire_at:  "expire_at",
}

var _telno_verify_code_fields = []string{
	telnoVerifyCodeMetaVar.F_code,
	telnoVerifyCodeMetaVar.F_created_at,
	telnoVerifyCodeMetaVar.F_expire_at,
}

// Slice
type TelnoVerifyCodeSlice []TelnoVerifyCode

func NewTelnoVerifyCodeSlice(cap int) *TelnoVerifyCodeSlice {
	s := TelnoVerifyCodeSlice(make([]TelnoVerifyCode, 0, cap))
	return &s
}

func (s TelnoVerifyCodeSlice) TableMeta() storage.TableMeta { return telnoVerifyCodeMetaVar }
func (s TelnoVerifyCodeSlice) Len() int                     { return len(s) }
func (s *TelnoVerifyCodeSlice) Slice() []TelnoVerifyCode    { return []TelnoVerifyCode(*s) }

func (s *TelnoVerifyCodeSlice) New(table string, index int, key string) (storage.Table, error) {
	for len(*s) <= index {
		*s = append(*s, TelnoVerifyCode{})
	}
	x := &((*s)[index])
	err := x.SetKey(key)
	return x, err
}

// View
type TelnoVerifyCodeView struct {
	TelnoVerifyCode
}

type TelnoVerifyCodeViewSlice []TelnoVerifyCodeView

func NewTelnoVerifyCodeViewSlice(cap int) *TelnoVerifyCodeViewSlice {
	s := TelnoVerifyCodeViewSlice(make([]TelnoVerifyCodeView, 0, cap))
	return &s
}

func (s TelnoVerifyCodeViewSlice) TableMeta() storage.TableMeta  { return telnoVerifyCodeMetaVar }
func (s TelnoVerifyCodeViewSlice) Len() int                      { return len(s) }
func (s *TelnoVerifyCodeViewSlice) Slice() []TelnoVerifyCodeView { return []TelnoVerifyCodeView(*s) }

func (s *TelnoVerifyCodeViewSlice) New(table string, index int, key string) (storage.Table, error) {
	if table == "telno_verify_code" {
		for len(*s) <= index {
			x := TelnoVerifyCode{}
			*s = append(*s, TelnoVerifyCodeView{TelnoVerifyCode: x})
		}
		x := &((*s)[index].TelnoVerifyCode)
		err := x.SetKey(key)
		return x, err
	}
	v := &((*s)[index])
	for t, x := range v.tables() {
		if t == table {
			err := x.SetKey(key)
			return x, err
		}
	}
	return nil, storage.ErrTableNotFoundInView
}

var (
	TelnoVerifyCodeViewVar  = TelnoVerifyCodeView{}
	telnoVerifyCodeViewRefs = map[string]storage.View{}
)

func (TelnoVerifyCodeView) TableMeta() storage.TableMeta { return telnoVerifyCodeMetaVar }
func (TelnoVerifyCodeView) Fields() storage.FieldList {
	return storage.FieldSlice(telnoVerifyCodeMetaVar.Fields())
}
func (TelnoVerifyCodeView) Refs() map[string]storage.View { return telnoVerifyCodeViewRefs }
func (view *TelnoVerifyCodeView) tables() map[string]storage.Table {
	m := make(map[string]storage.Table)
	m["telno_verify_code"] = &view.TelnoVerifyCode
	return m
}
