//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// NOTE: auto generated by midc, DON'T edit
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
package server

import (
	"github.com/mkideal/pkg/netutil/httputil"
)

func (svr *Server) registerAllHandlers(mux *httputil.ServeMux) {
	svr.registerHandler(mux, makeRouter("account_exist"), "GET", svr.handleAccountExist)
	svr.registerHandler(mux, makeRouter("authorize_check"), "GET", svr.handleAuthorizeCheck)
	svr.registerHandler(mux, makeRouter("authorize"), "POST", svr.handleAuthorize)
	svr.registerHandler(mux, makeRouter("auto_signup"), "POST", svr.handleAutoSignup)
	svr.registerHandler(mux, makeRouter("help"), "GET", svr.handleHelp)
	svr.registerHandler(mux, makeRouter("signin"), "POST", svr.handleSignin)
	svr.registerHandler(mux, makeRouter("signout"), "POST", svr.handleSignout)
	svr.registerHandler(mux, makeRouter("signup"), "POST", svr.handleSignup)
	svr.registerHandler(mux, makeRouter("token_auth"), "POST", svr.handleTokenAuth)
	svr.registerHandler(mux, makeRouter("token"), "POST", svr.handleToken)
	svr.registerHandler(mux, makeRouter("user"), "GET", svr.handleUser)
}
