//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// NOTE: auto generated by midc, DON'T edit
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
package server

import (
	"github.com/mkideal/pkg/netutil/httputil"
)

func (svr *Server) registerAllHandlers(mux *httputil.ServeMux) {
	svr.registerHandler(mux, "/v1/access_token", "POST", svr.handleAccessToken)
	svr.registerHandler(mux, "/v1/account_exist", "GET", svr.handleAccountExist)
	svr.registerHandler(mux, "/v1/authorize_check", "GET", svr.handleAuthorizeCheck)
	svr.registerHandler(mux, "/v1/authorize", "POST", svr.handleAuthorize)
	svr.registerHandler(mux, "/v1/auto_signup", "POST", svr.handleAutoSignup)
	svr.registerHandler(mux, "/v1/help", "GET", svr.handleHelp)
	svr.registerHandler(mux, "/v1/signin", "POST", svr.handleSignin)
	svr.registerHandler(mux, "/v1/signout", "POST", svr.handleSignout)
	svr.registerHandler(mux, "/v1/signup", "POST", svr.handleSignup)
	svr.registerHandler(mux, "/v1/token_info", "POST", svr.handleTokenInfo)
	svr.registerHandler(mux, "/v1/user", "GET", svr.handleUser)
}
